### ISSUE TITLE
Setup packer

### ISSUE THREAD

**Issue by sassanh** [ubopod/ubo-app#43] opened 2024-02-09 12:46 UTC
To contribute to the headlessness of the project, let's create Ubo images based on Raspberry Pi OS Bookworm. This way users will be able to flash this image to an SD card and boot it into Ubo without needing any additional steps.

**Comment by mehrdadfeller** [comment] 2024-02-09 16:12
This is a duplicate of issue https://github.com/ubopod/ubo-app/issues/13. You can close both once completed.

**Closed** 2024-02-09 16:15 UTC
